name: CI/CD Branch by Environment

on:
  push:
    branches: [ main, staging, production ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Simular Compilación (Build)
        run: |
          echo "Compilando el código de la rama: ${{ github.ref_name }}"
          echo "Generando artefacto con la configuración de la rama..."
          echo "APP_${{ github.ref_name }}_BUILD" > artifact.txt
          cat config.json >> artifact.txt

      - name: Ejecutar Pruebas Automatizadas (Test & Start)
        run: |
          echo "Arrancando la aplicación para validar que no haya errores fatales..."
          node app.js
          echo "Pruebas pasaron exitosamente."

      - name: Simular Despliegue (Deploy)
        run: |
          echo "Desplegando la aplicación en el servidor correspondiente..."
          echo "¡Despliegue completado!"
